Task 1
DrozdMary/Tasks pull request #1
Opened 2024-01-17 11:28 UTC by DrozdMary

2024-01-24 11:48 UTC, zaitsevv requested changes

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_connector.py
> +                "create table  IF NOT EXISTS rooms ( id int NOT NULL, name varchar(50), primary key(id) )"
Соблюдай один код стайл - либо ты пишешь всё в нижнем регистре как `create table`, или все ключевые слова пишешь в верхнем как `IF NOT EXISTS`

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_connector.py
> +from logger import logger
Импорты из python core должны идти до импортов библиотек
```
from logger import logger

import mysql.connector
from config import ...
```

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_loader.py
> +            for items in data:
это работает, но можно проще, посмотри `json_populate_recordset`
![image](https://github.com/DrozdMary/Tasks/assets/82774766/dbccdf6e-c4f0-47df-9f5b-90ca12d7dd2c)

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_loader.py
> +            for items in data:
`{json}` это все данные из json файла в виде питон строки

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_loader.py
> +            for items in data:
или ещё можешь посмотреть в сторону `COPY`

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/db_connector.py
> +                "create table  IF NOT EXISTS students( birthday datetime, id int primary key, name char(100), room int, "
лучше все строковые запросы вынести в отдельные файлы

2024-01-24 11:48 UTC, zaitsevv commented on task_1/src/sql_script_executor.py
> +            for i in range(len(columns)):
почитай про dict comprehension и перепиши этот цикл используя его

2024-01-24 11:49 UTC, zaitsevv commented
И добавь везде аннотации типов

2024-01-24 13:54 UTC, DrozdMary commented on task_1/src/db_loader.py
> +            for items in data:
да , намного проще, но это для PostgreSQL... в MySQL  "Not supported"(

2024-01-26 09:04 UTC, zaitsevv approved these changes

2024-01-28 08:55 UTC, merged